ZKVM-1: fix ProveKeccakRequest alignment issues (#2834)
The original error reported:

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.20.0/src/internal.rs:33:3:
cast_slice>TargetAlignmentGreaterAndInputNotAligned
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at ./rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: bytemuck::internal::something_went_wrong
             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.20.0/src/internal.rs:33:3
   3: bytemuck::internal::cast_slice
             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.20.0/src/internal.rs:257:15
   4: bytemuck::cast_slice
             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.20.0/src/lib.rs:377:12
   5: risc0_zkvm::host::server::prove::keccak::prove_keccak
             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-1.2.1/src/host/server/prove/keccak.rs:35:37
   6: <risc0_zkvm::host::server::prove::prover_impl::ProverImpl as risc0_zkvm::host::server::prove::ProverServer>::prove_keccak
             at ./usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-1.2.1/src/host/server/prove/prover_impl.rs:255:9
...
```

Where the issue here is that the input is just `Vec<u8>` and a reference
to is being cast to `&[[u64; 25]]` which should require 8 byte
alignment, but is not guaranteed by the `Vec<u8>`.